services:
  db:
    image: percona/percona-server
    environment:
      MYSQL_DATABASE: 'l20'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
    - '3308:3308'
    expose:
    - '3308'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/db:/etc/mysql/conf.d
      - ./data/var/log/mysql:/var/log/mysql
      - ./shared:/shared
      - ./backup:/backup
    networks:
      - p20

  php:
    build:
      context: ./context/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - p20

networks:
  p20:
    driver: bridge